### ISSUE TITLE
Questions about computing dice

### ISSUE THREAD

**Issue by caiyu6666** [iolag/UPD_study#4]
Thanks for your great work. I have a question about computing dice in this code.

In `utilies/metrics.py`, function `compute_best_dice()` concatenates all the testing samples together to compute the dice score, instead of computing the dice of each sample one by one.

I am wondering whether this operation is reasonable as the dice score is usually caculated for each case seperately. Thanks.

**Comment by iolag** [comment]
Hey, 

We followed Baur et al. in reporting the best possible dataset-wise dice. I agree that it seems a little unconventional but consider the fact that unsupervised methods provide continuous instead of binary outputs. As dice requires binary maps, you need to decide on a good performing threshold. This is no arbitrary task in an unsupervised setting (see discussion on their Open Problems section), as you probably need to use your test set for that. Baur et al. searched for the best possible threshold for the dataset-wise dice, instead of going with the less general volume-wise or slice-wise approaches. Now, the value of using and reporting such a metric is up for debate, but that's another discussion :)

**Comment by caiyu6666** [comment]
I got it. Thank you very much!
